### ISSUE TITLE
request for /mgmt results in 404

### ISSUE THREAD

**Issue by svendhhh** [git-lfs/lfs-test-server#64]
I'm running the test server on Windows 10 from the binary like this:

    D:\Program Files\git-lfs-test-server>SET LFS_ADMIN=admin & SET LFS_ADMINPASS=password & lfs-test-server.exe
2017-08-01T11:49:54Z KWS007 lfs[8588] [proc.go:111]: pid=8588 addr=tcp://:8080 version=0.3.0 fn=main msg=listening
2017-08-01T11:50:08Z KWS007 lfs[8588] [server.go:362]: method=GET url=/mgmt status=404 request_id=a72ed098-0c0c-6e53-a40b-0e90a3ee2f4b

And then requesting:

    http://localhost:8080/mgmt

But this returns "Not Found" and a 404 is registered (see log above). Should there be some html files along with the executable, or are the (missing) admin page all generated code?

**Comment by ttaylorr** [comment]
@svendhhh thanks for opening this and sorry that you're having trouble! I think the issue is that `LFS_ADMINUSER` and `LFS_ADMINPASS` aren't set correctly. From the code<sup>[[1](https://github.com/git-lfs/lfs-test-server/blob/master/server.go#L203)] [[2](https://github.com/git-lfs/lfs-test-server/blob/master/mgmt.go#L28)] [[3](https://github.com/git-lfs/lfs-test-server/blob/master/mgmt.go#L67-L71)]</sup>:

```go
return func(w http.ResponseWriter, r *http.Request) {
  if Config.AdminUser == "" || Config.AdminPass == "" {
    writeStatus(w, r, 404)
    return
  }

  // ...
}
```

The only way to get a 404 out of `GET`-ing the `/mgmt` path would be to have a `Config.AdminUser` or `Config.AdminPass` be empty. This can occur when either of those variables aren't found in the environment.

Double checking, __the correct environment variable for `Config.AdminUser` is `LFS_ADMINUSER`, not `LFS_ADMIN`. 

Can you try:

```
SET LFS_ADMINUSER=admin & SET LFS_ADMINPASS=password & lfs-test-server.exe
```

and let me know if that works?

**Comment by svendhhh** [comment]
Thank you!
Setting the variables resulted in the 401 authorisation prompt instead of the 404.
However, I had to remove the spaces between the "admin" and "&" and "password" and "&". Not sure if something isn't being trimmed properly somewhere? :)
Thank you again for your help.
